remote_theme: "zerostaticthemes/jekyll-serif-theme@gh-pages"
baseurl: "/jekyll-serif-theme/"
name: HoneycutCoffee
title: HoneycutCoffee
include: ["_main"]
description: >
    HoneycutCoffee

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins: 
    - jekyll-environment-variables
