remote_theme: "zerostaticthemes/jekyll-serif-theme@v1.4"
baseurl: "/jekyll-serif-theme/"
name: HoneycutCoffee
title: HoneycutCoffee
include: ["_main"]
description: >
    HoneycutCoffee
plugins: 
    - jekyll-environment-variables
