remote_theme: "zerostaticthemes/jekyll-serif-theme@v1.4"
minimal_mistakes_skin: "dark"
name: HoneycutCoffee
title: HoneycutCoffee
include: ["_main"]
description: >
    HoneycutCoffee
plugins: ["jekyll-include-cache", "jekyll-feed"]
